### ISSUE TITLE
Error in fld.frq = high tide dataset ('ht') must be numeric

### ISSUE THREAD

**Issue by MvdS91** [troyhill/VulnToolkit#4]
Hi, I've been using the VulnToolkit and it has really helped a lot! 
However, for some reason today, the flooding frequency is not working anymore for some subsets of my data (it was working fine yesterday).
Can you help me resolve the issue?

Below the error code and str() of the data I'm using
 `Error in fld.frq(z = ffseason2014$elev, ht = season2014.HL[season2014.HL$tide ==  : 
     high tide dataset ('ht') must be numeric`

--> all 2014. HL works for the flooding frq
`> str(all2014.HL)`
`data.frame':	1410 obs. of  4 variables:`
` $ level: num  5.55 -0.34 5.63 -0.39 5.42 -0.44 6 -0.3 5.92 -0.43 ...`
` $ time : POSIXct, format: "2014-01-01 02:50:00" "2014-01-01 10:10:00" "2014-01-01 15:10:00" "2014-01-01 22:40:00" ...`
 `$ tide : chr  "H" "L" "H" "L" ...`
` $ tide2: chr  "LH" "HL" "HH" "LL" ...`
`> ffall2014     <- data.frame(elev = seq(from = 4, to = 6, by = 0.005))`
`> ffall2014$frq <- fld.frq(z = ffall2014$elev, ht = all2014.HL[all2014.HL$tide == "H", "level"]) `

--> season 2014 below is not working for the flooding freq 
`> str(season2014.HL)`
`Classes ‘data.table’ and 'data.frame':	947 obs. of  4 variables:`
` $ level: num  5.69 -0.57 6.06 -0.23 6.03 -0.72 5.89 -0.67 5.77 -0.75 ...`
` $ time : POSIXct, format: "2014-03-01 03:20:00" "2014-03-01 10:40:00" "2014-03-01 15:30:00" "2014-03-01 22:50:00" ...`
` $ tide : chr  "H" "L" "H" "L" ...`
` $ tide2: chr  "LH" "LL" "HH" "HL" ...`
` - attr(*, ".internal.selfref")=<externalptr> `
`> ffseason2014     <- data.frame(elev = seq(from = 4, to = 6, by = 0.005))`
`> ffseason2014$frq <- fld.frq(z = ffseason2014$elev, ht = season2014.HL[season2014.HL$tide == "H", "level"]) `
`Error in fld.frq(...)`

--> spring2014. HL works for the flooding frq
`> str(spring2014.HL)`
`data.frame':	407 obs. of  4 variables:`
 `$ level: num  -0.23 6.03 -0.72 5.89 -0.67 5.77 -0.75 6.04 -0.33 6 ...`
 `$ time : POSIXct, format: "2014-03-01 22:50:00" "2014-03-02 03:50:00" "2014-03-02 11:40:00" "2014-03-02 16:10:00" ...`
 `$ tide : chr  "L" "H" "L" "H" ...`
 `$ tide2: chr  NA "HH" "LL" "LH" ...`

-->new spring 2014 below is not working for th flooding freq 
`> str(newspring2014.HL)`
`Classes ‘data.table’ and 'data.frame':	391 obs. of  4 variables:`
` $ level: num  -0.23 6.03 -0.72 5.89 -0.67 5.77 -0.75 6.04 -0.33 6 ...`
` $ time : POSIXct, format: "2014-03-01 22:50:00" "2014-03-02 03:50:00" "2014-03-02 11:40:00" "2014-03-02 16:10:00" ...`
` $ tide : chr  "L" "H" "L" "H" ...`
` $ tide2: chr  "HL" "HH" "LL" "LH" ...`
` - attr(*, ".internal.selfref")=<externalptr> `

The only inconsistency between the datasets that works/don't work is the "- attr(*, ".internal.selfref")=<externalptr>  ", but I can't find anything that shows this might be the cause of the error

Thanks in advance!

**Comment by troyhill** [comment]
It looks like the code that isn't working is sending `fld.frq` a data.table, but that shouldn't be a problem in isolation. The `fld.frq` function checks whether `ht` is numeric, and that is returning FALSE in the case of your data.table inputs. 

Here is my effort to re-create your issue and experiment with data.table inputs: 

```
library(VulnToolkit)
library(data.table)

HT.NL     <- HL(level = NL_6min_2013[, 2], time = NL_6min_2013[, 1], tides = "all")
HT.NL.dt <- data.table(HT.NL) # convert it to data.table
fld.frq(z = 0, ht = HT.NL.dt$level, units = "percent") # works with data.table input
fld.frq(z = 0, ht = HT.NL.dt$level[grep(x = HT.NL.dt$tide, pattern = "H")], units = "percent") # also works with a subset of the data.table

### I can get an error here, but I'm not sure this is similar to what you're doing
ht1      <- as.data.table(HT.NL[, 1]) # let's try a single-column data.table
fld.frq(z = 0, ht = ht1, units = "percent") # this errors out, bc techically ht1 is a full data.table and not a single column

fld.frq(z = 0, ht = ht1$V1, units = "percent") # a solution here is to specify a single column in the data.table
```

If you can re-create your problem with the package data (NL_6min_2013) then I should be able to reproduce it and be more helpful.

**Comment by MvdS91** [comment]
Hi! Thanks for your quick response.

I've tried my script with the package data and it works again. No idea what happened earlier.
For my own data, I've used "Import dataset as Excel" and that seems to fix the issue (instead of read.csv2)

Thanks again !

**Comment by troyhill** [comment]
This is my favorite kind of problem - one that resolves itself!
